# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160913_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 9, 13, 17, 46, 35, 171436, tzinfo=utc)),
        ),
    ]
